---
sidebar: sidebar 
permalink: create-knowledgebase.html 
keywords: ai, chatbot, creating, knowledge base 
summary: 在部署AI基础架构并从FSx for ONTAP数据存储库中确定要集成到知识库中的数据源后、即可使用Workload Factory构建知识库。在此步骤中、您还将定义AI特征并创建对话开场白。 
---
= 创建知识库
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在部署AI基础架构并从FSx for ONTAP数据存储库中确定要集成到知识库中的数据源后、即可使用Workload Factory构建知识库。在此步骤中、您还将定义AI特征并创建对话开场白。

无需集成企业的数据源、即可使用知识库。在这种情况下、与知识库集成的应用程序将仅提供互联网上公开提供的信息的结果。这称为_public mode_integration。

在大多数情况下、您需要将组织中的数据源集成到知识库中。这种方式称为_Enterprise mode_integration、因为它可以提供企业的知识。



== 创建并配置知识库

知识库定义了一些特征、例如、要用来创建知识库的基础AI模型和嵌入格式。

.步骤
. 登录到Workload Factory。
. 在AI Workloads (AI工作负载)磁贴中、选择*部署和管理*。
. 从“Knowledge Bases”(知识库)选项卡中，选择“*添加知识库*”。
. 在Define Knowledge Base页面上、配置知识库设置：
+
.. *Name*：输入要用于知识库的名称。
.. *Description*：输入知识库的详细说明。
.. *嵌入模型*：嵌入模型定义了如何将数据转换为知识库的矢量嵌入。Workload Factory支持以下型号：
+
*** T人 嵌入G1 -文本
*** T人 嵌入文本v2
*** 第1代多模态嵌入
+
请注意、您必须已启用Amazon Brock中的嵌入模型。

+
https://aws.amazon.com/bedrock/titan/["详细了解Amazon大力孙"^]



.. *聊天模式*：从集成在Amazon Brock中的Claude聊天模式中进行选择。请注意、您必须已启用Amazon Brock中的聊天模式。
+
详细了解可帮助您进行选择的型号： https://aws.amazon.com/bedrock/claude/["anthpic的克洛德在亚马逊基岩"^]

.. *对话开场白*：选择是否要提供最多四个对话开场提示、这些提示将显示给与使用此知识库的聊天机器人进行交互的用户。建议您启用此设置。
+
如果您激活了启动对话器、则默认情况下会选中"自动模式"。只有在将数据源添加到知识库后、才能启用"手动模式"。link:manage-knowledgebase.html["了解如何修改知识库设置"](英文)

.. *FSx for ONTAP文件系统*：定义新知识库时，Workload Factory会创建一个新的Amazon FSx for NetApp ONTAP卷来存储该卷。选择现有文件系统名称以及要创建新卷的SVM (也称为Storage VM)。
.. *Snapshot policy*：从Workload Factory存储清单中定义的现有策略列表中选择一个Snapshot策略。
+
如果不存在所需的快照策略、则可以 https://docs.netapp.com/us-en/ontap/data-protection/create-snapshot-policy-task.html["创建快照策略"]在包含此卷的Storage VM上执行此操作。



. 选择*创建知识库*将知识库添加到GenAI中。
+
在向导的下一页中、您可以选择将数据源添加到新知识库中、或者在此处结束此过程而不添加数据源。建议您选择*添加数据源*，然后立即添加一个或多个数据源。





== 向知识库添加数据源

您可以添加一个或多个数据源、以便使用组织的数据填充知识库。

.关于此任务
支持的最大数据源数为10。

.步骤
. 选择*添加数据源*后，将显示*选择文件系统*页。
. *选择文件系统*：选择数据源文件所在的FSx for ONTAP文件系统，然后选择*下一步*。
. *选择卷*：选择数据源文件所在的卷，然后选择*下一步*。
+
选择使用SMB协议存储的文件时、您需要输入Active Directory信息、其中包括域、IP地址、用户名和密码。

. *选择数据源*：根据文件的保存位置选择数据源位置。该卷可以是整个卷，也可以是卷中的特定文件夹或子文件夹，然后选择*Next*。
. *定义AI参数*：在*Chunking strasy*部分中，定义在将数据源与知识库集成时，GenAI引擎如何将数据源内容拆分成块。您可以选择以下策略之一：
+
** *多句拆分*：将数据源中的信息组织为句子定义的区块。您可以选择每个区块包含多少个句子(最多100个)。
** *基于重叠的区块*：将数据源中的信息组织为字符定义的区块，这些区块可以重叠相邻区块。您可以选择每个区块的字符大小、以及每个区块与相邻区块重叠的程度。您可以将区块大小配置为50到3000个字符、并将重叠百分比配置为1到99%。
+

NOTE: 选择较高的重叠百分比会显著增加存储需求、但检索准确性只会稍有提高。



. 在*权限感知*部分(仅当您选择的数据源位于使用SMB协议的卷上时才可用)中、您可以启用或禁用此选择：
+
** *已启用*：访问此知识库的聊天机器人用户只会从他们有权访问的数据源获得查询响应。
** *已禁用*：聊天机器人用户将使用所有集成数据源的内容接收响应。


. 选择*Add*将此数据源添加到您的知识库中。


.结果
数据源开始嵌入到您的知识库中。当数据源完全嵌入时、状态将从"嵌入"更改为"嵌入"。

向知识库添加单个数据源后、您可以在本地的Chatbot模拟器窗口中对其进行测试、并进行任何必要的更改、然后再将聊天机器人提供给用户。您也可以按照相同的步骤向知识库添加其他数据源。
