---
settings:
  name: GenAI
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: GenAI文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 新增功能
      url: "/whats-new.html"
  - title: 了解适用于GenAI的BlueXP  工作负载工厂
    entries:
    - title: 了解适用于GenAI的BlueXP  工作负载工厂
      url: "/general/ai-workloads-overview.html"
    - title: NetApp GenAI引擎的组件
      url: "/general/genai-engine-instance.html"
  - title: 使用GenAI为Amazon Brock构建知识库
    entries:
    - title: 开始使用
      entries:
      - title: 快速入门
        url: "/knowledge-base/quick-start-knowledge-base.html"
      - title: 知识库要求
        url: "/knowledge-base/requirements-knowledge-base.html"
      - title: 确定要添加到知识库中的数据源
        url: "/knowledge-base/identify-data-sources-knowledge-base.html"
      - title: 部署GenAI基础架构
        url: "/knowledge-base/deploy-infrastructure.html"
    - title: 创建知识库
      url: "/knowledge-base/create-knowledgebase.html"
    - title: 测试知识库
      url: "/knowledge-base/test-knowledgebase.html"
    - title: 激活身份验证
      url: "/knowledge-base/activate-authentication.html"
    - title: 发布知识库
      url: "/knowledge-base/publish-knowledgebase.html"
    - title: 使用外部示例聊天机器人应用程序
      url: "/knowledge-base/example-chatbot-application.html"
    - title: 创建基于RAG的AI应用程序
      url: "/knowledge-base/create-application.html"
    - title: 接下来可以执行的操作
      url: "/knowledge-base/whats-next.html"
  - title: 使用GenAI为Amazon Q Business创建连接器
    entries:
    - title: 开始使用
      entries:
      - title: 快速入门
        url: "/connector/quick-start-connector.html"
      - title: 知识库要求
        url: "/connector/requirements-connector.html"
      - title: 确定要添加到知识库中的数据源
        url: "/connector/identify-data-sources-connector.html"
      - title: 部署GenAI基础架构
        url: "/connector/deploy-infrastructure.html"
    - title: 创建适用于Amazon的NetApp ONTAP连接器Q
      url: "/connector/define-connector.html"
  - title: 管理GenAI
    entries:
    - title: 管理GenAI基础架构
      url: "/general/manage-infrastructure.html"
    - title: 管理知识库
      url: "/knowledge-base/manage-knowledgebase.html"
    - title: 管理连接器
      url: "/connector/manage-connector.html"
    - title: 管理数据源
      url: "/general/manage-data-source.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/support-registration.html"
    - title: 故障排除
      url: "/general/troubleshooting.html"
    - title: 获取帮助
      url: "/get-help.html"
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
