---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 了解工作负载工厂AI工作负载功能的新增功能。 
---
= 新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解工作负载工厂生成型AI工作负载功能的新增功能。



== 2024年11月3日



=== 使用数据防护屏蔽个人身份信息

生成型AI工作负载引入了由BlueXP  分类提供支持的数据防护功能。数据防护功能可识别和屏蔽个人身份信息(Personal可识别信息、Personal可识别信息、Personal可识别信息)、帮助您保持合规性并增强敏感组织数据的安全性。

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#create-and-configure-the-knowledge-base["创建知识库"]

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["了解BlueXP分类"^]



== 2024年9月29日



=== 为知识库卷提供快照和还原支持

现在、您可以通过创建知识库的时间点副本来保护生成性AI工作负载数据。这样、您就可以保护数据、防止意外丢失或测试对知识库设置所做的更改。您可以随时还原知识库卷的先前版本。

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume["为知识库卷创建快照"]

https://review.docs.netapp.com/us-en/workload-genai_29-sept-24-release/manage-knowledgebase.html#restore-a-snapshot-of-a-knowledge-base-volume["还原知识库卷的快照"]



=== 暂停计划的扫描

现在、您可以暂停计划的数据源扫描。默认情况下、生成性AI工作负载每天都会扫描每个数据源、以便将新数据导入到每个知识库中。如果您不希望(例如在测试或还原快照期间)导入最新更改、您可以随时暂停计划的扫描并恢复它们。

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html["管理知识库"]



=== 现在、知识库可支持数据保护卷

现在、在选择知识库卷时、您可以选择属于NetApp SnapMirror复制关系的数据保护卷。这样、您就可以将知识库存储在已受SnapMirror复制保护的卷上。

https://docs.netapp.com/us-en/workload-genai/identify-data-sources.html["确定要集成到知识库中的数据源"]



== 2024年9月1日



=== 其他分块策略

生成型AI工作负载现在支持对数据源执行多句分块和基于重叠的分块。



=== 为每个知识库提供专用卷

现在、生成性AI工作负载会为每个新知识库创建一个专用的Amazon FSx for NetApp ONTAP卷、从而为每个知识库启用单独的快照策略、并提高对故障和数据中毒的防护能力。



== 2024 年 8 月 4 日



=== Amazon CloudWatch Logs集成

生成型AI工作负载现已与Amazon CloudWatch Logs集成、使您能够监控生成型AI工作负载日志文件。



=== 聊天机器人应用程序示例

通过NetApp Workload Factory GenAI示例应用程序、您可以在基于Web的聊天机器人应用程序中直接与发布的NetApp Workload Factory知识库进行交互、从而测试身份验证和从该知识库中检索的结果。



== 2024年7月7日



=== 适用于GenAI的工作负载工厂初始版本

初始版本支持开发一个知识库、该知识库可通过嵌入组织的数据进行自定义。您的用户可以通过聊天机器人应用程序访问知识库。此功能可确保准确、相关地回答组织特定的问题、从而提高所有用户的满意度和工作效率。
