---
sidebar: sidebar 
permalink: connector/requirements-connector.html 
keywords: ai, chatbot, prerequisites, bedrock, fsx for ontap, prerequisites, requirements 
summary: '在构建知识库之前、请确保已正确设置工作负载工厂和AWS。其中包括拥有AWS登录凭据、部署了一个FSx for ONTAP文件系统(其中包含您要集成到知识库中的数据源)、访问Amazon B基石AI服务等。' 
---
= GenAI连接器要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建适用于Amazon的NetApp ONTAP连接器之前、请确保已正确设置工作负载工厂和AWS



== 基本GenAI要求

GenAI具有您的环境在开始使用之前需要满足的一般要求。

工作负载出厂登录和帐户:: 您需要 https://docs.netapp.com/us-en/workload-setup-admin/sign-up-saas.html["在Workload Factory中设置一个帐户"^]使用其中一个登录 https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
AWS 凭据和权限:: 您需要向工作负载工厂添加具有读/写权限的AWS凭据、这意味着您将在_Read/Write_模式下对GenAI使用工作负载工厂。
+
--
目前不支持_Basic_模式和_read-only _模式权限。

设置凭据时、选择如下所示的权限后、您将拥有管理FSx for ONTAP文件系统以及部署和管理GenAI EC2实例以及知识库和聊天机器人所需的其他AWS资源的完全访问权限。

https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["了解如何将AWS凭据添加到工作负载工厂"^]

--




== NetApp ONTAP Connector for Amazon的要求问题

确保您的环境满足Amazon Q Business连接器的以下特定要求。

Amazon Q Business应用程序:: 您需要创建Amazon Q Business应用程序或使用现有应用程序。
+
--
* 确保应用程序位于您的一个AWS区域中。
* 确保应用程序已安装 https://docs.aws.amazon.com/amazonq/latest/qbusiness-ug/select-retriever.html["已创建索引"^]。
* 确保应用程序未处于故障状态。


--
FSx for ONTAP文件系统:: 对于ONTAP文件系统、至少需要一个FSx：
+
--
* NetApp GenAI引擎将使用一个文件系统(如果不存在、则会创建一个文件系统)来存储有关连接器的信息。
+
此FSx for ONTAP文件系统必须使用FlexVol卷。不支持 FlexGroup 卷。

* 一个或多个文件系统将包含要添加到连接器的数据源。
+
一个FSx for ONTAP文件系统可同时用于这两种用途、也可以使用多个FSx for ONTAP文件系统。

* 您需要了解AWS FSx for ONTAP文件系统所在的AWS区域、VPC和子网。
* 您需要考虑要应用于此部署中的AWS资源的标记键/值对(可选)。
* 您需要知道密钥对信息、以便安全地连接到NetApp AI引擎实例。


https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["了解如何部署和管理FSx for ONTAP文件系统"^]

--

